lang = en

[CheetahGenerator]
    encoding = utf8
    [[html]]
        [[[index]]]
            template = index.html.tmpl
    [[javascript]]
        [[[init]]]
            template = javascript/init.js.tmpl
        [[[gauges]]]
            template = 

[CopyGenerator]
    copy_once = javascript/*.js

[Generators]
        generator_list = weewx.cheetahgenerator.CheetahGenerator, weewx.reportengine.CopyGenerator
