name: Run master analyze and test matrix

on:
  workflow_dispatch:

jobs:
  analyze-test:
    uses: weewx-extensions/development-tools/.github/workflows/analyze-test-matrix.yml@master
    with:
      module-name: 'mqttloopdata'
      #pip-list: 'paho-mqtt'
      #package-list: 'mosquitto'
      weewx-extension: 'https://github.com/chaunceygardiner/weewx-loopdata/'
      # weewx-extension-ver: 'master'
      unit-test: false
      function-test: false
      integration-test: true
      e2e-test: false
      #flake-extra-parms: '--exclude tests'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      CODACY_API_TOKEN: ${{ secrets.CODACY.API_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}